name: smart_break
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0

  cupertino_icons: ^1.0.8
  
  # Map and location dependencies - ACTUALIZADAS
  google_maps_flutter: ^2.14.0
  geolocator: ^11.0.1
  
  # State management
  provider: ^6.1.1
  
  # UI dependencies
  flutter_rating_bar: ^4.0.1

  # Database - ACTUALIZADA
  sqflite: ^2.3.0
  
  path: ^1.8.3

  # Maps - ACTUALIZADA
  flutter_map: ^8.0.0

  # Storage - ACTUALIZADA
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true