name: smart_break
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Map and location dependencies
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  
  # State management
  provider: ^6.1.1
  
  # UI dependencies
  flutter_rating_bar: ^4.0.1

  # COMPATIBLE VERSION
  sqflite: ^2.3.3+1
  
  path: ^1.8.3

  # COMPATIBLE VERSION
  flutter_map: ^7.0.0

  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
